#!/usr/bin/env python3
"""Node that extracts VLM features."""
from dataclasses import dataclass, field

import rospy
import semantic_inference_ros
import numpy as np

from semantic_inference_python import Config

from semantic_inference_msgs.msg import FeatureVectorsStamped
from semantic_inference_ros import Conversions, SyncImagesWorkerConfig
from sensor_msgs.msg import Image, CompressedImage


@dataclass
class VLMFeatureNodeConfig(Config):
    """Configuration for CLIPFeaturesNode."""

    worker: SyncImagesWorkerConfig = field(default_factory=SyncImagesWorkerConfig)
    playback_mode: bool = False


class DummyVLMNode:
    """Dummy nodde to publish empty feats."""

    def __init__(self):
        """Initialize the node."""
        self.config = semantic_inference_ros.load_from_ros(VLMFeatureNodeConfig, ns="~")
        rospy.loginfo(f"'{rospy.get_name()}': Initializing with {self.config.show()}")

        self._vlm_pub = rospy.Publisher(
            "relation_features",
            FeatureVectorsStamped,
            queue_size=20,
        )

        self._worker = semantic_inference_ros.SyncImagesWorker(
            self.config.worker,
            [
                "color/image_raw",
            ],
            [Image] if not self.config.playback_mode else [CompressedImage],
            self._spin_once,
        )
        rospy.loginfo(f"'{rospy.get_name()}': Initialized")

    def _spin_once(self, header, _: np.ndarray):
        self._vlm_pub.publish(Conversions.to_stamped_features(header, [], None))

    def spin(self):
        """Wait until ros shuts down."""
        self._worker.spin()


def main():
    """Start a node."""
    rospy.init_node("dummy_vlm_node")
    semantic_inference_ros.setup_ros_log_forwarding()

    node = DummyVLMNode()
    node.spin()


if __name__ == "__main__":
    main()
